name: Build and Publish

on:
  push:
    branches: 
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: NPM install
      run: npm install
    - name: build
      run: npm run build
    - name: publish
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        FOLDER: .
        BRANCH: gh-pages
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
